# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pippin-Games
email: studiopippingames@gmail.com
lang: en_US
description: >- # this means to ignore newlines until "baseurl:"
  Indie, Funny, Amazing Game Studio from Brazil
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pippingames.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Ricardo Luiz, ricardoluiz508@gmail.com
logo: /assets/logo_pippin.png
twitter_username: pippin_games
github_username:  pippin_games
social:
  name: Pippin Games
  links: 
    - https://twitter.com/pippin_games
    - https://www.facebook.com/PippinGames

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed  
  - jekyll-paginate-v2

# Pagination Settings - instale o plugin "gem install jekyll-paginate-v2"
pagination:
  enabled: true
  per_page: 1
  permalink: '/page/:num/'  
  limit: 0
  sort_field: 'date'
  sort_reverse: true

#escopos deafult para facilitar acesso a resources
defaults:
  - scope:
      path: "assets/images/monstender/screenshort"
    values:
      monstender_images: true
  - scope:
      path: "assets/images/kdd/screenshort"
    values:
      kdd_images: true  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
